[package]
name = "cursed-server"
version = "0.1.0"
edition = "2021"

[dependencies]
tonic = "0.12"
prost = "0.13"
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }
log = "0.4.22"
pretty_env_logger = "0.5.0"
rerun = "0.17.0"

[build-dependencies]
tonic-build = "0.12"