[package]
name = "cursed-server"
version = "0.1.0"
edition = "2021"

[dependencies]
websocket = "0.27.1"
tokio = { version = "1", features = ["full"] }
warp = "0.3"
futures-util = "0.3.30"
log = "0.4.22"
pretty_env_logger = "0.5.0"
futures = "0.3.30"
