/**
 * @fileoverview gRPC-Web generated client stub for cursed
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v5.27.3
// source: cursed.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as cursed_pb from './cursed_pb'; // proto import: "cursed.proto"


export class TopicServiceClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'binary';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorRequestTopicList = new grpcWeb.MethodDescriptor(
    '/cursed.TopicService/RequestTopicList',
    grpcWeb.MethodType.UNARY,
    cursed_pb.TopicListRequest,
    cursed_pb.TopicListResponse,
    (request: cursed_pb.TopicListRequest) => {
      return request.serializeBinary();
    },
    cursed_pb.TopicListResponse.deserializeBinary
  );

  requestTopicList(
    request: cursed_pb.TopicListRequest,
    metadata?: grpcWeb.Metadata | null): Promise<cursed_pb.TopicListResponse>;

  requestTopicList(
    request: cursed_pb.TopicListRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: cursed_pb.TopicListResponse) => void): grpcWeb.ClientReadableStream<cursed_pb.TopicListResponse>;

  requestTopicList(
    request: cursed_pb.TopicListRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: cursed_pb.TopicListResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/cursed.TopicService/RequestTopicList',
        request,
        metadata || {},
        this.methodDescriptorRequestTopicList,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/cursed.TopicService/RequestTopicList',
    request,
    metadata || {},
    this.methodDescriptorRequestTopicList);
  }

}

