version: '3.8'

services:
  cursed-ws-bridge:
    build:
      context: ./cursed-ws-bridge
    ports:
      - "3030:3030"
    environment:
      - RUST_LOG=${RUST_LOG:-info}  # Default to info if not set
    command:
      - "--address=0.0.0.0"  # Listen on all interfaces in container
      - "--port=3030"
      - "--send-rate-hz=10.0"
    restart: unless-stopped

  cursed-ws-web:
    build:
      context: ./cursed-ws-web
    ports:
      - "80:80"
    restart: unless-stopped
    depends_on:
      - cursed-ws-bridge
    # Optional environment variables if needed
    # environment:
    #   - SOME_ENV_VAR=value

# Add a volume for persistent data if needed
# volumes:
#   data-volume: 