version: '3.8'

services:
  cursed-ws-bridge:
    build:
      context: ./cursed-ws-bridge
    ports:
      - "3030:3030"
    environment:
      - RUST_LOG=debug  # More verbose logging for development
    command:
      - "--address=0.0.0.0"
      - "--port=3030"
      - "--send-rate-hz=10.0"
    restart: unless-stopped

  cursed-ws-web-dev:
    image: oven/bun:1
    working_dir: /app
    volumes:
      - ./cursed-ws-web:/app
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
    command: ["bun", "run", "dev", "--", "--host", "0.0.0.0"]
    depends_on:
      - cursed-ws-bridge 